vlbg_websocket_entry:
    resource: "@VlbgWebsocketBundle/Resources/config/routing/entry.xml"
    prefix:   /entry

vlbg_websocket_event:
    resource: "@VlbgWebsocketBundle/Resources/config/routing/event.xml"
    prefix:   /event

